### ISSUE TITLE
Querying meta data fails

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#2]
`.tables` doesn't list tables

`.schema` doesn't display a schema

**Comment by danshearer** [comment]
With the feature/all-tests branch:

exam@example:~/lumosql/lumosql/bld-LMDB_0.9.9$ ./sqlite3 
SQLite version 3.7.17 d1d3ea01f60e8ed00c7
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite>  create table gnergle(quxx varchar(5), splanpf bigint);
sqlite> .schema
CREATE TABLE gnergle(quxx varchar(5), splanpf bigint);

which is good.

sqlite> .tables
Segmentation fault (core dumped)

which is not.

The problem has been found and fixed as part of making lmdb used exclusively as a library. The fix has not yet been committed.

**Comment by danshearer** [comment]
Fixed in later LMDB+SQLite 3.8.1 I think... moved to https://lumosql.org/src/lumosql/tktview/f0d6de3ebd0205b33df325a8da4eca4b23d14f8a
