### ISSUE TITLE
Results from sqlite test/async*.test are interesting

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#21]
As a potential candidate to add to our benchmarking:
https://github.com/sqlite/sqlite/blob/master/test/async2.test

**Comment by danshearer** [comment]
There are 5 async* tests

**Comment by danshearer** [comment]
I've done some sample runs of the TCL tests, and I don't think it is really stressing concurrent access.  https://github.com/sqlite/sqlite/tree/master/mptest seems to be more along those lines but I haven't done sample runs of it (mptest hasn't changed in 6 years, and all the references to it seem to be in the context of windows, if that means anything.)

**Comment by danshearer** [comment]
Moved notes to https://lumosql.org/src/lumosql/wiki?name=lumo-benchmarking-testing&p .
