### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#22]
So that other contributors know the process.

It might be good if this include setup steps on Gentoo or Arch Linux.

Ideally it might even include instructions for opening a PR from the command line.

**Comment by maxwell-k** [comment]
@danshearer are you handling this one?

I am happy to test or proof read if it helps.

**Comment by danshearer** [comment]
Yes I'll take this one.

Pull Requests are a github feature but git has a somewhat similar "request-pull" command.

This explains how to do PRs with some clumsiness using only git:
https://hackernoon.com/how-to-git-pr-from-the-command-line-a5b204a57ab1

However I'm also looking at hub, https://hub.github.com/ . I'm not sure if that is dumbing it down too much.
