### ISSUE TITLE
Track SQLite upstream more closely

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#23]
Right now LumoSQL is using a version of SQLite from 2013 - 3.7.17.

As a project we do not necessarily have to track every single SQLite release. We do desire to be more up to date than 2013.

One suggestion is that we "use a release of SQLite from the current year". For 2020 that would be [SQLite 3.31.0](https://github.com/sqlite/sqlite/releases/tag/version-3.31.0) or later.

At the moment I understand that a contributor is working on a patch that removes the use of LMDB global variables or internal implementation details in our code. One actual result is that all (?) of the tests pass after applying this patch. This patch should also make it easier to update to a recent SQLite version.

**Comment by maxwell-k** [comment]
@danshearer I hope I have captured the discussion accurately above.

**Comment by danshearer** [comment]
Very much done/underway. Closed with a pleased flourish :-)
