### ISSUE TITLE
Missing tag in SQLite repo when cloned by Makefile 

### ISSUE THREAD

**Issue by philtweir** [LumoSQL/archive1-LumoSQL-on-github#24]
When building LumoSQL via the Makefile on a freshly cloned repo, git checks out `version-3.30.1` - this tag is not available, and the Makefile errors out.

# Steps to Reproduce

1. `git clone https://github.com/LumoSQL/LumoSQL/`
2. `cd LumoSQL`
3. `make`

```
$ make
...
test -d src-SQLite || \
git clone --shallow-since 2013-05-19 --branch release \
	https://github.com/sqlite/sqlite.git src-SQLite
git -C src-SQLite checkout version-3.30.1
error: pathspec 'version-3.30.1' did not match any file(s) known to git
make: *** [Makefile:42: bld-SQLite-3.30.1] Error 1
```

### Versions

* LumoSQL commit: 3ab144
* git: 2.20.1

**Comment by maxwell-k** [comment]
I can reproduce this on `debian:buster`.
