### ISSUE TITLE
Kudos - Thanks for an amazing project!

### ISSUE THREAD

**Issue by andrewluetgers** [LumoSQL/archive1-LumoSQL-on-github#32]
Just saw your FOSDEM talk https://fosdem.org/2020/schedule/event/lumosql/ and am so happy someone is resurrecting this idea! 

I am doing research on cheaply running serverless databases that scale cheaply with ssd rather than demanding more and more ram. Additionally I want users to be able to downloaded and run their databases locally for the benefit of data ownership, reproducibility and preventing platform lock-in. This looks to be a perfect platform for pursuing these goals. Excited to follow your progress!!

**Comment by danshearer** [comment]
Andrew thanks very much, it means a lot to know this is getting interest already. I'd be glad to discuss your use case further. It sounds like you want to use the binary database files as a transport medium. For that LMDB is likely to give you some wins straight away (no WAL, reduced risk of corruption) but still internal integrity checks are needed (In SQLite and every other major database.) We're looking at that now.

Your use case sounds a bit like some of the human genomics datasets, where they also ship around the binary databases.

If you're doing LumoSQL testing then for the next week or so the branch you want is feature/all-tests which has a patch that makes all SQLite tests pass using LMDB as the btree/paging replacement.

**Comment by maxwell-k** [comment]
@andrewluetgers thank you for the encouragement! I hope we can deliver something useful to you.

**Comment by danshearer** [comment]
Closing, having banked the nice warm feelings. Thanks Andrew.
