### ISSUE TITLE
The readme talks about a feature/benchmarking branch that doesn't seem to exist

### ISSUE THREAD

**Issue by santagada** [LumoSQL/archive1-LumoSQL-on-github#35]
Hi,

The project readme mentions a feature/benchmarking branch, is it not published or has been replaced by something else?

**Comment by maxwell-k** [comment]
@santagada yes you're right. That branch has been merged and the results are available at https://lumosql.github.io/LumoSQL/ 

That branch added the code in the `benchmarking` folder, which is a wrapper to help us publish comparisons between different versions. This isn't polished but it is functional. The latest set of results from these comparisons are at https://lumosql.github.io/LumoSQL/

This is an active area for us right not so I hope we have more to share soon.

**Comment by maxwell-k** [comment]
NodeJS 12 is the active long term support (LTS) version:
https://nodejs.org/en/about/releases/

**Comment by santagada** [comment]
Just so that I understand, the results mean 3.30 is faster than lumosql in all benchmarks except insert?
