### ISSUE TITLE
Identify a web application or framework for benchmarking

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#38]
As a part of our plans to benchmarking LumoSQL, its various backends, SQLite and alternative implementations we would like to identify a suitable application.

The application or framework will rely on a database backend. By measuring the performance of the application or system, we hope understand more about the performance of the database backends.

Essential criteria:

- popular web application or framework in a well known language
- command line interface for performance testing
- performance testing must exercise a database
- supports either SQLite or MariaDB/MySQL

Desirable criteria:

- has support for both SQLite and MariaDB/MySQL engines and
- is easy to database swap engine

**Comment by danshearer** [comment]
I have added a lot to the benchmarking section in https://github.com/LumoSQL/LumoSQL/blob/master/doc/prior-art.md . This is a pretty surprising area.

I have looked at the DB testing layers in the develop of several languages, which is a lot less up-to-date and regularly-run than one might think.

**Comment by danshearer** [comment]
Not needed - we have a much better way of doing it now. See https://lumosql.org/src/lumosql/doc/trunk/doc/lumo-test-build.md
