### ISSUE TITLE
LumoSQL needs to append an ID to SQLite version numbers/strings

### ISSUE THREAD

**Issue by danshearer** [LumoSQL/archive1-LumoSQL-on-github#39]
We need to be able to tell we are dealing with LumoSQL while still retaining full SQLite version information. At minimum this needs to be the sqlite commandline to avoid confusion. Care will be needed with internal data structures, but probably SQLITE_SOURCE_ID can be changed with impunity since correct behaviour will be to modify since it will not reflect any upstream version.

I feel hesitant to change the constants in eg https://sqlite.org/c3ref/libversion.html

**Comment by maxwell-k** [comment]
I would like to agree a solution that we fix for a period. In this project's short history we've changed the output of `sqlite3 --version` twice already, for the last time see fbc462e0420a6f5a61c720794e1ea81a5db8edc5.

What are you trying to achieve @danshearer? I'd like to start with a documented set of requirements or a specification here. I think it would be wrong to focus on implementation details; I may be closer to these.

The current output of the LumoSQL `sqlite3 --version` is:

```
3.7.17 58d2267edc5c0a013fd61114e659377343614a42 LMDB_0.9.16 5d67c6aed16366ddcfac77eb6a166928a257ab7b
```

Four parts separated by a space:

1. SQLite version number
2. SHA1 of current LumoSQL git checkout
3. LMDB release tag
4. SHA1 corresponding to above

Does item 2 meet the minimum requirements in the issue description?


<details>
<summary>Steps to reproduce LumoSQL sqlite --version output</summary>

```sh
podman pull quay.io/keith_maxwell/lumosql-build:ubuntu
podman run -v .:/srv:Z lumosql-build:ubuntu /usr/bin/make -C /srv
podman run -v .:/srv:Z lumosql-build:ubuntu /srv/bld-LMDB_0.9.16/sqlite3 --version
```

</details>

**Comment by danshearer** [comment]
Fixed
