### ISSUE TITLE
Setting default cache size results in unknown operation

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#4]
This applies to all SQL statements, after setting `default_cache_size`:

```
$ echo "SELECT * FROM no_such_table;" | ./sqlite3 no_pragma.db
Error: near line 1: no such table: no_such_table
$ echo "PRAGMA default_cache_size=2000;" | ./sqlite3 pragma.db
$ echo "SELECT * FROM no_such_table;" | ./sqlite3 pragma.db
Error: near line 1: unknown operation
```

**Comment by danshearer** [comment]
Moved to https://lumosql.org/src/lumosql/tktview/f16cf7a42e2fdf7d9425ee0c036403fab94108f0

**Comment by likern** [comment]
> > @danshearer Have you found any of those databases?
> 
> Yes I have. I will tell you here where we are up to, but we need your help because it is a large task.
> 
> I have had the pleasure of working with [Karl Malbrain](https://github.com/malbrain) on his implementation of Blink Trees. As of a few days ago, the following commands will build a program called "standalone" which is a demonstrator of two types of indexing: Blink (ie Btrees with Blink concurrency) and Adaptive Radix trees:
> 
> ```shell
> git clone https://github.com/malbrain/database
> cd database
> git clone https://github.com/malbrain/rwlock
> git clone https://github.com/malbrain/Hi-Performance-Timestamps
> git clone https://github.com/malbrain/mutex
> # from now on, 'git clone --recurse' will work in the database directory
> # for updates if Karl has pushed any
> rm -rf alpha/   # this isn't meant to be here any more
> sh ./build
> ```
> 
> The README contains a terse description of what the demonstration program is supposed to do, and so far the code appears to follow the theory. This has definitely not been incorporated into LumoSQL, but it is a potential candidate. I'm sure Karl would consider any pull requests for documentation.
> 
> > Could you recommend such a literature about Radix Trees and Fractal Trees?
> 
> First I recommend you try something simpler, but still not simple: learn about modern locking and latches in Btrees using the Blink algorithms. And for this we have not only Karl's work, but also production Postgres code. Here is some reading, all of which is freely available online:
> 
> * Classic Btrees. There are many sources for this, it's basic compsci. They are implemented in all three backends that LumoSQL supports today: classic SQLite; LMDB and BDB.
> * The original Blink paper: P. Lehman and S. Yao, Efficient Locking for Concurrent Operations on B-Trees, ACM Transactions on Database Systems, Vol 6, No. 4, December 1981, pp 650-670
> * A follow paper that filled in details, especially node deletion: V. Lanin and D. Shasha, A Symmetric Concurrent B-Tree Algorithm, Proceedings of 1986 Fall Joint Computer Conference, pp 380-389
> * Postgres nbtree: The foregoing Blink algorithm papers are great, but they are not an implementation. Postgres [nbtree](https://github.com/postgres/postgres/tree/c30f54ad732ca5c8762bb68bbe0f51de9137dd72/src/backend/access/nbtree) is an implementation which adds constraints for concurrency in a real-world database, and an additional traversal mode, among other things.
> * Karl Malbrain's [Concurrency Paper](https://www.researchgate.net/publication/46585073_A_Blink_Tree_latch_method_and_protocol_to_support_synchronous_node_deletion) and his code discussed above implements the Lehman & Yao plus the Lannin & Sasha algorithms, but abstracts out the node locking mechanism to operating system primitives. (This PDF cannot be read by standalone open source PDF viewers that I have found, but is rendered by in-browser viewers in Firefox and Chrome.)
> 
> All of the above is about improving concurrent access while still maintaining database guarantees. It also does not really take us out of the 20th century. In the 21st century, many things have changed which means algorithms need to change. Some of the new factors include: SSD hardware preferring larger block sizes; relative access times between primary and secondary storage are smaller; 21st century L1 cache sizes are immensely larger; on-chip parallelism is immense; on-chip asymmetry is becoming more common; network bandwidth is much higher even on embedded nodes; network latency can be much lower.
> 
> To accommodate 21st century needs we need to look at changes. The ones LumoSQL has identified so far are:
> 
> * Single level store. This is a 20th century concept (apparently in Multics??) but is only implemented in LMDB that I know of. This is at a lower level than tree algorithms. LMDB implements a more-or-less classic btree. So we started with LMDB, as you know.
> * Fractal Trees. As a start you can study the code and related papers around Tokutek, whose code is in MongoDB. We're still working through this. (What might seem to be a software patent problem with fractal trees appears so far not to be an issue.)
> 
> Since LumoSQL is trying to be a working reference platform as well as an experimental testbed, these questions are very much about real-world applications.
> 
> You can help by contributing what you have learned, and any codebases that we have overlooked.
> 
> Would you be willing to try out the LumoSQL benchmarking tool and let us know the results from your setup?

Thank you for great response. 
I do not use LumoSQL, I asked because I wanted to implement my own simple database. I will dive into reading articles you recommend.
