### ISSUE TITLE
Decision about URLs

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#42]
In my view we require:

1. A decision about our desired public URLs
2. Provisioning of any appropriate repositories: setup and access permissions
3. Certainty for a three month period, so through to 9 June 2020

Other work including changes to or configuration of DNS is out of scope for this issue and should be handled separately.

## Context / history / background

- originally the code for benchmarking was a separate repository; by request it was moved into [`LumoSQL/LumoSQL`](https://github.com/LumoSQL/LumoSQL)

- we decided to use GitHub pages to publish:

  - website including written documentation, diagrams, video thumbnails
  - benchmarking results

  These represent outputs from two separate work streams within the project.

- technical information about GitHub pages is available at <https://help.github.com/en/github/working-with-github-pages/about-github-pages>

- capitalisation in the URLs below is important

- if we own `example.com` GitHub pages allows us to point `example.com` at `lumosql.github.io`

- version 1 of the benchmarking results are available at https://lumosql.github.io/LumoSQL/

## Illustrative options

_The second and later URLs are simply examples_

- <https://lumosql.github.io> / <https://example.com>

  - unauthenticated this is a 404 at present
  - an organisation site
  - [`LumoSQL/LumoSQL.github.io`](https://github.com/LumoSQL/LumoSQL.github.io) (not created yet)

- <https://lumosql.github.io/LumoSQL/> / <https://example.com/LumoSQL> / <https://example.com>

  - LumoSQL Benchmarking Version 1 right now
  - a project site
  - [`LumoSQL/LumoSQL`](https://github.com/LumoSQL/LumoSQL)

- <https://lumosql.github.io/benchmarking/>

  - 404 at present
  - a project site
  - [`LumoSQL/benchmarking`](https://github.com/LumoSQL/benchmarking) (not created yet)

- <https://lumosql.github.io/benchmarking-preview/>

  - 404 at present
  - a project site
  - [`LumoSQL/benchmarking-preview`](https://github.com/LumoSQL/benchmarking) (not created yet)
  - https://github.com/LumoSQL/benchmarking-preview/ (not created yet)

- …

**Comment by danshearer** [comment]
https://github.com/LumoSQL/lumosql.github.io now exists, containing a copy of the markdown files and images from https://github.com/LumoSQL/doc/www (but not bin/ or Makefile etc). That means https://lumosql.github.io is now live. doc/www/Makefile needs to have a new target called "publish" to make the copy to  https://github.com/LumoSQL/lumosql.github.io . The capitalisation can be changed since there are no manual modifications made to this tree meaning it is regenerated each time. 

We can move these docs down one level as soon as there is fresh benchmarking to publish as well.

**Comment by danshearer** [comment]
Very much done; more needed, but the LumoDoc project participants will help with that... welcome to you all.
