### ISSUE TITLE
Known issue with index sizes in sqlightning

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#5]
See https://github.com/LMDB/sqlightning/issues/1

**Comment by danshearer** [comment]
This part of the ongoing discussion about where to intercept SQLite APIs. We should be at a high enough level so that the fix for this (probably chained keys as hyc said in the bug report referenced above) applies to all storage backends. That suggests higher up the stack than where libkv would go.

**Comment by danshearer** [comment]
The backend abstraction layer design so far provides large key support for the backends that need it (eg LMDB does but RocksDB does not.)

**Comment by danshearer** [comment]
Not a bug. Moved to https://lumosql.org/src/lumosql/wiki?name=lumosql-storage-api . It isn't a bug because we are implementing generic key handling in the storage API, and that also involves some sensitivity into the different ways MVCC is implemented by various K-V stores.
